-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 11:10:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`typeUtilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`typeUtilisateur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`typeUtilisateur` (
  `idtypeUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `nomTypeUtilisateur` VARCHAR(45) NULL,
  PRIMARY KEY (`idtypeUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`produit` ;

CREATE TABLE IF NOT EXISTS `mydb`.`produit` (
  `idproduit` INT NOT NULL AUTO_INCREMENT,
  `prix` VARCHAR(45) NULL,
  `taille` VARCHAR(45) NULL,
  `modele` VARCHAR(45) NULL,
  `typeUtilisateur_idtypeUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idproduit`, `typeUtilisateur_idtypeUtilisateur`),
  INDEX `fk_produit_typeUtilisateur1_idx` (`typeUtilisateur_idtypeUtilisateur` ASC),
  CONSTRAINT `fk_produit_typeUtilisateur1`
    FOREIGN KEY (`typeUtilisateur_idtypeUtilisateur`)
    REFERENCES `mydb`.`typeUtilisateur` (`idtypeUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`commande` ;

CREATE TABLE IF NOT EXISTS `mydb`.`commande` (
  `idcommande` INT NOT NULL AUTO_INCREMENT,
  `dateCommande` DATE NULL,
  `dateLivraison` VARCHAR(45) NULL,
  `destinataire` VARCHAR(45) NULL,
  `commandecol` VARCHAR(45) NULL,
  `quantiteCommande` INT NULL,
  `produit_idproduit` INT NOT NULL,
  `produit_typeUtilisateur_idtypeUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idcommande`, `produit_idproduit`, `produit_typeUtilisateur_idtypeUtilisateur`),
  INDEX `fk_commande_produit1_idx` (`produit_idproduit` ASC, `produit_typeUtilisateur_idtypeUtilisateur` ASC),
  CONSTRAINT `fk_commande_produit1`
    FOREIGN KEY (`produit_idproduit` , `produit_typeUtilisateur_idtypeUtilisateur`)
    REFERENCES `mydb`.`produit` (`idproduit` , `typeUtilisateur_idtypeUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`utilisateur` (
  `idutilisateur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `telephone` INT NULL,
  `email` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NULL,
  `code_postal` INT NULL,
  `ville` VARCHAR(45) NULL,
  `pays` VARCHAR(45) NULL,
  `region` VARCHAR(45) NULL,
  `commande_idcommande` INT NULL,
  PRIMARY KEY (`idutilisateur`),
  INDEX `fk_client_commande_idx` (`commande_idcommande` ASC),
  CONSTRAINT `fk_client_commande`
    FOREIGN KEY (`commande_idcommande`)
    REFERENCES `mydb`.`commande` (`idcommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`stock` ;

CREATE TABLE IF NOT EXISTS `mydb`.`stock` (
  `idstock` INT NOT NULL AUTO_INCREMENT,
  `quantiteStock` INT NULL,
  `nomStock` VARCHAR(45) NULL,
  `commande_idcommande` INT NOT NULL,
  `commande_produit_idproduit` INT NOT NULL,
  `commande_produit_typeUtilisateur_idtypeUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idstock`, `commande_idcommande`, `commande_produit_idproduit`, `commande_produit_typeUtilisateur_idtypeUtilisateur`),
  INDEX `fk_stock_commande1_idx` (`commande_idcommande` ASC, `commande_produit_idproduit` ASC, `commande_produit_typeUtilisateur_idtypeUtilisateur` ASC),
  CONSTRAINT `fk_stock_commande1`
    FOREIGN KEY (`commande_idcommande` , `commande_produit_idproduit` , `commande_produit_typeUtilisateur_idtypeUtilisateur`)
    REFERENCES `mydb`.`commande` (`idcommande` , `produit_idproduit` , `produit_typeUtilisateur_idtypeUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entrepot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`entrepot` ;

CREATE TABLE IF NOT EXISTS `mydb`.`entrepot` (
  `identrepot` INT NOT NULL AUTO_INCREMENT,
  `nomEntrepot` VARCHAR(45) NULL,
  `stock_idstock` INT NOT NULL,
  PRIMARY KEY (`identrepot`, `stock_idstock`),
  INDEX `fk_entrepot_stock1_idx` (`stock_idstock` ASC),
  CONSTRAINT `fk_entrepot_stock1`
    FOREIGN KEY (`stock_idstock`)
    REFERENCES `mydb`.`stock` (`idstock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modele`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`modele` ;

CREATE TABLE IF NOT EXISTS `mydb`.`modele` (
  `idmodele` INT NOT NULL AUTO_INCREMENT,
  `nomModele` VARCHAR(45) NULL,
  `produit_idproduit` INT NOT NULL,
  `produit_typeUtilisateur_idtypeUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idmodele`, `produit_idproduit`, `produit_typeUtilisateur_idtypeUtilisateur`),
  INDEX `fk_modele_produit1_idx` (`produit_idproduit` ASC, `produit_typeUtilisateur_idtypeUtilisateur` ASC),
  CONSTRAINT `fk_modele_produit1`
    FOREIGN KEY (`produit_idproduit` , `produit_typeUtilisateur_idtypeUtilisateur`)
    REFERENCES `mydb`.`produit` (`idproduit` , `typeUtilisateur_idtypeUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
