-- MySQL Script generated by MySQL Workbench
-- Thu Apr  2 00:30:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`commande` ;

CREATE TABLE IF NOT EXISTS `mydb`.`commande` (
  `idcommande` INT NOT NULL AUTO_INCREMENT,
  `dateCommande` DATE NULL,
  `quantiteCommande` INT NULL,
  PRIMARY KEY (`idcommande`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`taille`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`taille` ;

CREATE TABLE IF NOT EXISTS `mydb`.`taille` (
  `idtaille` INT NOT NULL AUTO_INCREMENT,
  `nomTaille` VARCHAR(45) NULL,
  `statut` VARCHAR(45) NULL,
  PRIMARY KEY (`idtaille`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`couleur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`couleur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`couleur` (
  `idcouleur` INT NOT NULL AUTO_INCREMENT,
  `nomCouleur` VARCHAR(45) NULL,
  `statut` VARCHAR(45) NULL,
  PRIMARY KEY (`idcouleur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`genre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`genre` (
  `idgenre` INT NOT NULL AUTO_INCREMENT,
  `nomGenre` VARCHAR(45) NULL,
  PRIMARY KEY (`idgenre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cat` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cat` (
  `idcat` INT NOT NULL AUTO_INCREMENT,
  `nomCat` VARCHAR(45) NULL,
  `statut` VARCHAR(45) NULL,
  PRIMARY KEY (`idcat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`produit` ;

CREATE TABLE IF NOT EXISTS `mydb`.`produit` (
  `idproduit` INT NOT NULL AUTO_INCREMENT,
  `nomProduit` VARCHAR(45) NULL,
  `descProduit` VARCHAR(45) NULL,
  `prixHTproduit` INT NULL,
  `refProduit` INT NULL,
  `vipProduit` VARCHAR(45) NULL,
  `noteProduit` INT NULL,
  `statut` VARCHAR(45) NULL,
  `commande_idcommande` INT NOT NULL,
  `taille_idtaille` INT NOT NULL,
  `couleur_idcouleur` INT NOT NULL,
  `genre_idgenre` INT NOT NULL,
  `Cat_idcat` INT NOT NULL,
  PRIMARY KEY (`idproduit`),
  INDEX `fk_produit_commande1_idx` (`commande_idcommande` ASC),
  INDEX `fk_produit_taille1_idx` (`taille_idtaille` ASC),
  INDEX `fk_produit_couleur1_idx` (`couleur_idcouleur` ASC),
  INDEX `fk_produit_genre1_idx` (`genre_idgenre` ASC),
  INDEX `fk_produit_Cat1_idx` (`Cat_idcat` ASC),
  CONSTRAINT `fk_produit_commande1`
    FOREIGN KEY (`commande_idcommande`)
    REFERENCES `mydb`.`commande` (`idcommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_taille1`
    FOREIGN KEY (`taille_idtaille`)
    REFERENCES `mydb`.`taille` (`idtaille`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_couleur1`
    FOREIGN KEY (`couleur_idcouleur`)
    REFERENCES `mydb`.`couleur` (`idcouleur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_genre1`
    FOREIGN KEY (`genre_idgenre`)
    REFERENCES `mydb`.`genre` (`idgenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_Cat1`
    FOREIGN KEY (`Cat_idcat`)
    REFERENCES `mydb`.`Cat` (`idcat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tabBU`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tabBU` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tabBU` (
  `idtabBU` INT NOT NULL AUTO_INCREMENT,
  `idBanque` INT NULL,
  PRIMARY KEY (`idtabBU`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`utilisateur` (
  `idutilisateur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `telephone` INT NULL,
  `email` VARCHAR(45) NULL,
  `code_postal` INT NULL,
  `ville` VARCHAR(45) NULL,
  `pays` VARCHAR(45) NULL,
  `statut` VARCHAR(45) NULL,
  `nomRue` VARCHAR(45) NULL,
  `numRue` VARCHAR(45) NULL,
  `tabBU_idtabBU` INT NOT NULL,
  `commande_idcommande` INT NOT NULL,
  PRIMARY KEY (`idutilisateur`),
  INDEX `fk_utilisateur_tabBU1_idx` (`tabBU_idtabBU` ASC),
  INDEX `fk_utilisateur_commande1_idx` (`commande_idcommande` ASC),
  CONSTRAINT `fk_utilisateur_tabBU1`
    FOREIGN KEY (`tabBU_idtabBU`)
    REFERENCES `mydb`.`tabBU` (`idtabBU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_commande1`
    FOREIGN KEY (`commande_idcommande`)
    REFERENCES `mydb`.`commande` (`idcommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`typeUtilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`typeUtilisateur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`typeUtilisateur` (
  `idtypeUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `utilisateur_idutilisateur` INT NOT NULL,
  PRIMARY KEY (`idtypeUtilisateur`),
  INDEX `fk_typeUtilisateur_utilisateur_idx` (`utilisateur_idutilisateur` ASC),
  CONSTRAINT `fk_typeUtilisateur_utilisateur`
    FOREIGN KEY (`utilisateur_idutilisateur`)
    REFERENCES `mydb`.`utilisateur` (`idutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entrepot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`entrepot` ;

CREATE TABLE IF NOT EXISTS `mydb`.`entrepot` (
  `identrepot` INT NOT NULL AUTO_INCREMENT,
  `nomEntrepot` VARCHAR(45) NULL,
  `qteEntrepot` INT NULL,
  `statut` VARCHAR(45) NULL,
  `produit_idproduit` INT NOT NULL,
  `commande_idcommande` INT NOT NULL,
  PRIMARY KEY (`identrepot`),
  INDEX `fk_entrepot_produit1_idx` (`produit_idproduit` ASC),
  INDEX `fk_entrepot_commande1_idx` (`commande_idcommande` ASC),
  CONSTRAINT `fk_entrepot_produit1`
    FOREIGN KEY (`produit_idproduit`)
    REFERENCES `mydb`.`produit` (`idproduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrepot_commande1`
    FOREIGN KEY (`commande_idcommande`)
    REFERENCES `mydb`.`commande` (`idcommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tva` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tva` (
  `idtva` INT NOT NULL AUTO_INCREMENT,
  `nomTva` VARCHAR(255) NULL,
  `statut` VARCHAR(45) NULL,
  PRIMARY KEY (`idtva`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`materiel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`materiel` ;

CREATE TABLE IF NOT EXISTS `mydb`.`materiel` (
  `idmateriel` INT NOT NULL AUTO_INCREMENT,
  `nomMateriel` VARCHAR(255) NULL,
  `statut` VARCHAR(45) NULL,
  PRIMARY KEY (`idmateriel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ville`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ville` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ville` (
  `idville` INT NOT NULL AUTO_INCREMENT,
  `cp` INT NULL,
  `ville` VARCHAR(255) NULL,
  `utilisateur_idutilisateur` INT NOT NULL,
  PRIMARY KEY (`idville`),
  INDEX `fk_ville_utilisateur1_idx` (`utilisateur_idutilisateur` ASC),
  CONSTRAINT `fk_ville_utilisateur1`
    FOREIGN KEY (`utilisateur_idutilisateur`)
    REFERENCES `mydb`.`utilisateur` (`idutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`regionDept`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`regionDept` ;

CREATE TABLE IF NOT EXISTS `mydb`.`regionDept` (
  `idregionDept` INT NOT NULL AUTO_INCREMENT,
  `numDept` INT NULL,
  `nomDept` VARCHAR(45) NULL,
  `nomRegion` VARCHAR(45) NULL,
  `utilisateur_idutilisateur` INT NOT NULL,
  PRIMARY KEY (`idregionDept`),
  INDEX `fk_regionDept_utilisateur1_idx` (`utilisateur_idutilisateur` ASC),
  CONSTRAINT `fk_regionDept_utilisateur1`
    FOREIGN KEY (`utilisateur_idutilisateur`)
    REFERENCES `mydb`.`utilisateur` (`idutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`banque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`banque` ;

CREATE TABLE IF NOT EXISTS `mydb`.`banque` (
  `idbanque` INT NOT NULL AUTO_INCREMENT,
  `nomBanque` VARCHAR(255) NULL,
  `tabBU_idtabBU` INT NOT NULL,
  PRIMARY KEY (`idbanque`),
  INDEX `fk_banque_tabBU1_idx` (`tabBU_idtabBU` ASC),
  CONSTRAINT `fk_banque_tabBU1`
    FOREIGN KEY (`tabBU_idtabBU`)
    REFERENCES `mydb`.`tabBU` (`idtabBU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
